uint8 grasp_config_no # the number of the grasping configuration to be used (0, 1, 2, 3)
float32 closing_position # the closing position in mm (0.0..30.00)
---
bool success   # indicate successful run of triggered service
string message # informational, e.g. for error messages